apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ .Release.Name }}-pvc
  namespace: {{ .Values.app_name.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app_name.disc_space }}