apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.elastic.name }}-kibana
  namespace: {{ .Values.elastic.namespace }}
spec:
  version: 8.12.1
  count: {{ .Values.kibana.replicaCount }}
  elasticsearchRef:
    name: {{ .Values.elastic.name }}
